service: snake-app-backend

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  autocompleteSearchAustralianSnakes:
    handler: handler.autocompleteSearchAustralianSnakes
    events:
      - http:
          path: autocompleteSearchAustralianSnakes
          method: get
  getSnakeDetails:
    handler: handler.getSnakeDetails
    events:
      - http:
          path: getSnakeDetails
          method: get
custom:
  # serverless offline plugin setup
  serverless-offline:
    httpPort: 4000
